steps:
  # Step 1: Create and activate virtual environment, install dependencies
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirement.txt  # Ensure your requirements.txt is in the repo

  # Step 2: Build the Docker image for Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jago-dev/jago-microservice'  # Replace with your image name
      - '.'

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "deafult"  # Replace with your Cloud Run service name
      - "--image"
      - "gcr.io/jago-dev/jago-microservice"  # Ensure the correct image name
      - "--region"
      - "us-central1"  # Replace with your preferred region
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"  # Adjust depending on your authentication preferences

  # Optional: Delete old Cloud Run revisions (if desired)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        revisions=$(gcloud run revisions list \
          --service my-app \
          --format 'value(METADATA.NAME)' \
          --sort-by '~METADATA.CREATION_TIMESTAMP')
        # Skip the most recent revision and delete others
        for revision in $(echo "$revisions" | tail -n +2); do
          gcloud run revisions delete "$revision" \
            --service default \
            --quiet
        done

options:
  logging: "CLOUD_LOGGING_ONLY"  # Use this valid logging option
