steps:
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirement.txt  

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jago-dev/jagopos-microservice'  
      - '.'

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "jagopos-microservice"  
      - "--image"
      - "gcr.io/jago-dev/jagopos-microservice" 
      - "--region"
      - "us-central1"  =
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"  

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        revisions=$(gcloud run revisions list \
          --service my-app \
          --format 'value(METADATA.NAME)' \
          --sort-by '~METADATA.CREATION_TIMESTAMP')
        # Skip the most recent revision and delete others
        for revision in $(echo "$revisions" | tail -n +2); do
          gcloud run revisions delete "$revision" \
            --service my-app \
            --quiet
        done

options:
  logging: "CLOUD_LOGGING_AND_STDOUT"  
