steps:
  # Step 1: Create and activate virtual environment, install dependencies
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirement.txt  # Ensure your requirements.txt is in the repo

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jago-dev-2/jago-microservice'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/jago-dev-2/jago-microservice'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'default'  # Replace with your service name
      - '--image'
      - 'gcr.io/jago-dev-2/jago-microservice'
      - '--region'
      - 'us-central1'  # Replace with your region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/jago-dev-2/jago-microservice'

  # Optional: Delete old Cloud Run revisions (if desired)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        revisions=$(gcloud run revisions list \
          --service default \
          --format 'value(METADATA.NAME)' \
          --sort-by '~METADATA.CREATION_TIMESTAMP')
        # Skip the most recent revision and delete others
        for revision in $(echo "$revisions" | tail -n +2); do
          gcloud run revisions delete "$revision" \
            --service default \
            --quiet
        done

options:
  logging: "CLOUD_LOGGING_ONLY"  # Use this valid logging option
