PRODUCT_FONT_FAMILY = "./fonts/Arial_Bold.ttf"
PRODUCT_FONT_SIZE = 50
PRODUCT_FONT_COLOR = "orange"

CATEGORY_FONT_FAMILY = "./fonts/Arial_Bold.ttf"
CATEGORY_FONT_SIZE = 90
CATEGORY_FONT_COLOR = "yellow"

STRIKE_OUT_SIZE = 10
STRIKE_OUT_COLOR = "red"
